### ISSUE TITLE
Spell correction

### ISSUE THREAD

**Issue by mantono** [mantono/DuplicateSearcher#6]
**What should be done?**
Correct spelling on words that are not spelled correctly, if a correct version can be recognized.

**When is it finished?**
When a given input of a set of words containing
- correctly spelled words
- incorrectly spelled words
- words that cannot be identified

returns
- correctly spelled words
- words that cannot be identified (flag these?)
  with no duplicate occurrences of words (hence a set).

**Issues it depends on:** #4

**Comment by antonfriedmann** [comment]
https://www.languagetool.org/

**Comment by mantono** [comment]
https://commons.apache.org/sandbox/commons-text/jacoco/org.apache.commons.text.similarity/LevenshteinDistance.java.html
